sudo: required

language: go

go_import_path: github.com/bosh-prometheus/bosh_exporter

services:
  - docker

env:
  matrix:
    - DOCKER_IMAGE_NAME=boshprometheus/bosh-exporter
  global:
    - secure: eQKO3aBd7jnCnBOwZMpicA1DV8zx6WSJ3FsJRK3bU8+YvScHC6dqPZkWeA8eV0h0RiETtC6JO6Yif/AtSLw//TbF3aZvoQMjVXB7UHSjWj4RClF879z89pAxkZNfO5HxIzj5nD2pCWUVxYbE24KIZeSpkwWj7Pf3fyIXdWgROM1/Jlu3LvnBy4bfL6r6vz5F0RCBz019mLUnlGuw1CW6bCAp0+yEG5ZkaLAaPgL4MSP/1uGV66iE0kgshqFdI8/UyAAvwi8szQRxK45Xtzvhm8a0sGQebAR38nWc9v9WuNPi82c7wCoJ9TpdkSxbjcQuBQErZBKBmIRGRsP+8UB0G1H0Wqb+FOp84SPBAgTOjOE4a6eGit2yby6zg7OyptVTlwLErmgK3oc411SMgWmCSyVm5UdtlDUj9VNEmCpLk7DwohALyRZTj8FaEOQRvCaaq4lvi+5FPWPTklgCHRYHW6LC9AZe1vHG8awfTFO58o3emLyocNJmpUS0tz8HOcPW4fPpBTsX54352AwSuttDMWgkfqY36DMJwVCOK6WPYXSQ1rzewGpIZc6FBFh48iIkX3wKTbU7B9WX0iBPJs18eRF7WyJ2WqydGsclKYLXn4FZOVKnIX7bfBV3N7eBtS1lfL/cKAwrU/dDBFIhVZ1XvrLXnKYDqVc+o2N/MMMOhks=
    - secure: PyZFkuiq1dSV2xZ40Ybg/kVEuJeCqV3u9Viqf3YhuPGHvvHdZD4WbJVlYOBoxM97dJnEst+LwJB64Rsc5IJ/mDIfGps/IAP9kuGFoFCetnn+OWoZCMaAFwpr9ztFQIO4AHfy1hSSZ+48v9lm8WKQW/BMIpqM70Itw5+F7V9SrLKrKqMEMSqtGOGj6rKpkmvBPBjnkOTyke4FiYeeLnNQz980AABd7QZS/8c+amVfrUm1YrDqIs8h7pMAXM7zyg0lPrpxSDAz6PJCi1FxVhdwFEnOFRE9PCnrCcCEjZ+UtwZvfq82Rqq2B5Ge/WYlVFdO4up3RxE8zUu3hs4mnoNp/E/VIoe2fCTJ+08hTwkkboWhbIhFlE+g0wkuq0ABYvNtiVdiuI0XIgqKjwMvKxcUUZmdpZcDet2O04RgeUJoitw+ESwye2bQKjgZPQbJxA7WEPO5/FUSgg896bYbatOD8kYF511Ltntb7oCNhdJksRvFEct1Weo4qUkOhedag1965qOGU5LUVCK68RazNCXGeTNUq9dC/hrcFV8COrV2An1fPx2wEj3iRB++koE8jli2iE6BcAVrpP/3nRAQVB9UYj8pR26qvRl1A7qr8vqC0iF0OWQ2zW1UVaAe410h4HzDqGIewxlxlVAYR2WWJmo8m4j/uCadvXqqTVE6h4vz2CI=

jobs:
  include:
    - stage: tests
      script: make test
    - stage: docker image
      script:
        - make crossbuild
        - ln -s .build/linux-amd64/bosh_exporter bosh_exporter
        - |
          if [ -n "$TRAVIS_TAG" ]; then
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$TRAVIS_TAG
          else
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
          fi
        - |
          if [[ "$TRAVIS_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            docker tag "$DOCKER_IMAGE_NAME:$TRAVIS_TAG" "$DOCKER_IMAGE_NAME:latest"
          fi
        - docker images
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push $DOCKER_IMAGE_NAME
          fi
